import './globals.css'
import { Navbar } from '@/components'
import { Manrope } from 'next/font/google'

const manrope = Manrope({ subsets: ['latin'], weight: [ '200', '300', '400', '500', '600', '700', '800'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
